'use strict';

// Approving or rejecting a pending signup, from a link in an email.
//
// These endpoints are unauthenticated by necessity: the administrator clicks
// them from a mail client, which carries no session. The token in the URL is
// therefore the entire credential, which forces three properties:
//
//   unguessable  256 bits from a CSPRNG, generated by the signup gate
//   single-use   consumed on the first click, so a forwarded mail is inert
//   expiring     12 hours, so an old mailbox is not a standing key
//
// Approving grants only the ability to *sign up*. It grants nothing inside the
// app: sync-user still decides what a person may do, and a newly provisioned
// user gets the least privileged profile with a zero approval limit. The worst
// case for a leaked token is an unwanted empty account, not an unwanted
// administrator.
//
// Note the escaping convention here differs from the Exide build: this file
// uses zqRaw, which returns a BARE escaped value, so the quotes belong in the
// SQL string. Exide's store.zq emits its own quotes. Mixing them up produces
// ''value'', which is not a string literal.

const TERMINAL = ['Approved', 'Rejected'];

function escapeHtml(value) {
  return String(value === null || value === undefined ? '' : value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/** A human opened this in a browser tab from an email, so answer with a page. */
function page(title, message, tone) {
  const colour = tone === 'good' ? '#127a3d' : tone === 'bad' ? '#b3261e' : '#555';
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)}</title></head>
<body style="font-family:system-ui,-apple-system,Segoe UI,sans-serif;
             display:grid;place-items:center;min-height:100vh;margin:0;background:#faf9f8">
  <div style="max-width:420px;padding:32px;text-align:center">
    <h1 style="color:${colour};font-size:20px;margin:0 0 8px">${escapeHtml(title)}</h1>
    <p style="color:#555;line-height:1.5;margin:0">${escapeHtml(message)}</p>
  </div>
</body></html>`;
}

/** Tokens are hex from the gate. Anything else was not issued here. */
function validToken(value) {
  return typeof value === 'string' && /^[0-9a-f]{32,128}$/.test(value);
}

function stamp(date) {
  const p = n => String(n).padStart(2, '0');
  return `${date.getUTCFullYear()}-${p(date.getUTCMonth() + 1)}-${p(date.getUTCDate())} ` +
         `${p(date.getUTCHours())}:${p(date.getUTCMinutes())}:${p(date.getUTCSeconds())}`;
}

/**
 * Find a decidable request.
 *
 * Returns a discriminated result rather than throwing: "this link was already
 * used" is an ordinary thing to tell somebody, not an error.
 */
async function loadPending(zcql, esc, token, nowMs) {
  const rows = await zcql(
    `SELECT ROWID, Email, Status, ExpiresAt FROM SignupRequests ` +
    `WHERE Token = '${esc(token)}'`
  );
  const row = (rows || []).map(r => r.SignupRequests).filter(Boolean)[0];

  if (!row) return { kind: 'unknown' };
  if (TERMINAL.includes(String(row.Status))) return { kind: 'used', row };

  // A row that cannot prove it is still valid does not get the benefit of the
  // doubt: a missing or unparseable expiry counts as expired.
  const expiry = row.ExpiresAt ? Date.parse(String(row.ExpiresAt).replace(' ', 'T') + 'Z') : NaN;
  if (!Number.isFinite(expiry) || expiry < nowMs) return { kind: 'expired', row };

  return { kind: 'ok', row };
}

/**
 * Decide a pending signup.
 *
 * `deps` carries everything touching the outside world so the tests can run
 * this for real: { zcql, esc, escId, now }.
 */
async function handle(token, status, deps) {
  const { zcql, esc, escId, now } = deps;

  if (!validToken(token)) {
    // The same answer as an unknown token, so probing reveals nothing about
    // which tokens exist.
    return { html: page('Link not valid', 'This link is not valid. It may have been mistyped.', 'bad') };
  }

  const nowMs = now();
  const found = await loadPending(zcql, esc, token, nowMs);

  if (found.kind === 'unknown') {
    return { html: page('Link not valid', 'This link is not valid. It may have been mistyped.', 'bad') };
  }
  if (found.kind === 'used') {
    return {
      html: page('Already decided',
        `This request was already ${String(found.row.Status).toLowerCase()}. ` +
        'Approval links work only once.', 'neutral')
    };
  }
  if (found.kind === 'expired') {
    return {
      html: page('Link expired',
        'This link has expired. Ask the person to try signing up again, ' +
        'which will send you a fresh one.', 'neutral')
    };
  }

  // Guarded on Status = 'Pending' as well as ROWID, so two clicks arriving
  // together cannot both take effect.
  await zcql(
    `UPDATE SignupRequests SET Status = '${esc(status)}', ` +
    `DecidedBy = 'link', DecidedAt = '${esc(stamp(new Date(nowMs)))}' ` +
    `WHERE ROWID = ${escId(found.row.ROWID)} AND Status = 'Pending'`
  );

  if (status === 'Approved') {
    return {
      html: page('Access approved',
        `${found.row.Email} can now sign in. They will have view-only access ` +
        'until you give them a role in Settings.', 'good')
    };
  }
  return {
    html: page('Request rejected',
      `${found.row.Email} has been refused and cannot sign in.`, 'bad')
  };
}

module.exports = { handle, loadPending, validToken, page, escapeHtml, stamp, TERMINAL };
